# Generated by Django 4.1.1 on 2022-09-27 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_host",
            field=models.BooleanField(default=False),
        ),
    ]
